# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: JaCoCo Code Coverage Report
      id: jacoco_reporter
      uses: PavanMudigonda/jacoco-reporter@v3.0
      with:
        coverage_results_path: ${{ github.workspace }}/build/reports/jacoco/testCoverage/testCoverage.xml
        coverage_report_name: Coverage
        coverage_report_title: JaCoCo
        github_token: ${{ secrets.GITHUB_TOKEN }}
        skip_check_run: true # set to true to skip the run and to avoid 65k problem
        minimum_coverage: 80
        fail_below_threshold: false
        publish_only_summary: false #set to false to generate full coverage report
      
    # uploads the coverage-report.md artifact  for offline viewing using VS Code
    - name: Upload Code Coverage Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: "*/coverage-results.md"
        retention-days: 1 
