# This is a basic workflow to help you get started with Actions #5

name: CI-TWO

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run Coverage
      run: ./gradlew testCoverage


    - name: Jacoco Report to PR
      id: jacoco
      uses: madrapps/jacoco-report@v1.1
      with:
        path: ${{ github.workspace }}/build/reports/jacoco/testCoverage/testCoverage.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 40
        min-coverage-changed-files: 60
        debug-mode: false
        
    - name: JaCoCo Code Coverage Report
      id: jacoco_reporter
      uses: PavanMudigonda/jacoco-reporter@v4.4
      with:
        coverage_results_path: ${{ github.workspace }}/build/reports/jacoco/testCoverage/testCoverage.xml
        coverage_report_name: Coverage
        coverage_report_title: JaCoCo
        github_token: ${{ secrets.GITHUB_TOKEN }}
        skip_check_run: true # set to false to publish check run
        minimum_coverage: 80
        fail_below_threshold: false # set to false to pass below even when threshold is not met
        publish_only_summary: false. #set to true to publish only summary to avoid 65k problem

    - name: Get the Coverage info
      run: |
        echo "Total coverage ${{ steps.jacoco.outputs.coverage-overall }}"
        echo "Changed Files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"
        
#     - name: construct coverage job summary markdown
#       run: |
#         cat > coverage_summary.md <<EOF
#           | Code Coverage Summary                      | Value                                                    |
#           |--------------------------------------------|----------------------------------------------------------|
#           | Code Coverage %                            | ${{ steps.jacoco_reporter.outputs.coverage_percentage }} |
#           | :heavy_check_mark: Number of Lines Covered | ${{ steps.jacoco_reporter.outputs.covered_lines }}       |
#           | :x: Number of Lines Missed                 | ${{ steps.jacoco_reporter.outputs.missed_lines }}        |
#           | Total Number of Lines                      | ${{ steps.jacoco_reporter.outputs.total_lines }}         |
#         EOF
        
    - name: create coverage job markdown
      run: |
        echo ${{ steps.jacoco_reporter.outputs.coverageSummary }} >> coverage_summary.md
        
    - name: publish summary
      run: |
        cat coverage_summary.md >> $GITHUB_STEP_SUMMARY

#     - name: publish coverage job summary markdown
#       run: |
#          cat coverage_summary.md >> $GITHUB_STEP_SUMMARY
